[2022-09-12T00:00:02.001+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: scrapping_etl.etl scheduled__2022-09-11T00:00:00+00:00 [queued]>
[2022-09-12T00:00:02.017+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: scrapping_etl.etl scheduled__2022-09-11T00:00:00+00:00 [queued]>
[2022-09-12T00:00:02.018+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-12T00:00:02.019+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-12T00:00:02.019+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-12T00:00:02.030+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): etl> on 2022-09-11 00:00:00+00:00
[2022-09-12T00:00:02.037+0000] {standard_task_runner.py:52} INFO - Started process 31605 to run task
[2022-09-12T00:00:02.047+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scrapping_etl', 'etl', 'scheduled__2022-09-11T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/job_dag.py', '--cfg-path', '/tmp/tmpcy4b8fpf', '--error-file', '/tmp/tmpkd5yb57w']
[2022-09-12T00:00:02.050+0000] {standard_task_runner.py:80} INFO - Job 17: Subtask etl
[2022-09-12T00:00:02.141+0000] {task_command.py:371} INFO - Running <TaskInstance: scrapping_etl.etl scheduled__2022-09-11T00:00:00+00:00 [running]> on host 71464bd58847
[2022-09-12T00:00:02.238+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=c.mendozar@outlook.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrapping_etl
AIRFLOW_CTX_TASK_ID=etl
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T00:00:00+00:00
[2022-09-12T00:00:33.951+0000] {logging_mixin.py:115} INFO - TOTAL INSERTED: 134 jobs
[2022-09-12T00:00:33.982+0000] {logging_mixin.py:115} INFO - TOTAL INSERTED: 0 jobs
[2022-09-12T00:00:33.983+0000] {logging_mixin.py:115} INFO - TOTAL NOT INSERTED: 134 jobs
[2022-09-12T00:00:33.997+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 78, in etl_jobs
    print('TOTAL JOBS INSERTED: {}'.format(len(load_jobs.inserted_ids)))
UnboundLocalError: local variable 'load_jobs' referenced before assignment
[2022-09-12T00:00:34.119+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=scrapping_etl, task_id=etl, execution_date=20220911T000000, start_date=20220912T000002, end_date=20220912T000034
[2022-09-12T00:00:34.221+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task etl (local variable 'load_jobs' referenced before assignment; 31605)
[2022-09-12T00:00:34.848+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-12T00:00:35.006+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
